name: StalkerWeapons
version: ${project.version}
main: ru.frostdelta.stalkerweapons.StalkerWeapons
authors: [FrostDelta123]
description: Stalker Weapons plugin
commands:
  weapongive:
    permission: stalkerweapons.weapongive
